### ISSUE TITLE
Diffs are not recognized properly

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck-web#105]
When I run `SimpleShowcaseIT` (current `master` on 8b9fd7268cc302a204023312f284a9fb18ff4e84) locally on my Mac, it is green. If I change just a little thing, e.g., the `<h1>` content in line 138 in the `retest.html` page, then I get 100 differences (of which are 109 unique) out of nowhere. This is extremely confusing since I only changed a single element. See attachements for details.

![bildschirmfoto 2018-11-15 um 16 26 07](https://user-images.githubusercontent.com/11643714/48562972-9d62e080-e8f3-11e8-953f-eb11ed70ee17.png)
![bildschirmfoto 2018-11-15 um 16 25 58](https://user-images.githubusercontent.com/11643714/48562971-9d62e080-e8f3-11e8-96bb-ccd682cec53c.png)

**Comment by roesslerj** [comment]
Yeah, this is basically a known problem and the reason for this is absolute outline coordinates. On the existing branch `relative-xy`, the result just contains the expected changes:


But then marking the screenshot doesn’t work anymore… because that still expects absolut values.

**Comment by roesslerj** [comment]
Now I get the expected changes. Still a lot, because missing elements are not aggregated (could show only parent ...), but way better (now only 18).
