### ISSUE TITLE
Formatting showcase HTML leads to multiple differences

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck-web#143]
Applying, e.g, the IntelliJ HTML formatter to

https://github.com/retest/recheck-web/blob/master/src/test/resources/pages/showcase/retest.html

leads to multiple differences. The formatter introduces line breaks, for instance

```html
<li><a href="https://www.retest.de/en/for-testers/test-automation-without-programming.html">Automation without Programming</a></li>
```

becomes

```html
<li><a href="https://www.retest.de/en/for-testers/test-automation-without-programming.html">Automation
    without Programming</a></li>
```

The rendered result within the browser isn't different. (We should probably look into the HTML specification.)

**Comment by modulo11** [comment]
Fixed with PR #152.
