### ISSUE TITLE
Rename 'ShouldIgnore' to 'Filter'

### ISSUE THREAD

**Issue by roesslerj** [retest/recheck-web#183]
The interface should be more general, i.e. filter only if something applies... this also allows for a general 'filter' functionality, e.g. in the GUI.

**Comment by beatngu13** [comment]
Shouldn't we move this to recheck and/or mark it as fixed due to https://github.com/retest/recheck/pull/168?

**Comment by roesslerj** [comment]
Implemented in recheck.
