### ISSUE TITLE
Package in mvn-rel.-1.0.0 not found

### ISSUE THREAD

**Issue by Wollewoll** [retest/recheck-web#193]
the Package de.retest.web.testutils are not found in your Maven Central Release.

<dependency>
    <groupId>de.retest</groupId>
    <artifactId>recheck-web</artifactId>
    <version>1.0.0</version>
</dependency>
![grafik](https://user-images.githubusercontent.com/48954586/55002772-76ba6200-4fd7-11e9-9d18-70e12ce799fd.png)

**Comment by beatngu13** [comment]
[`de.retest.web.testutils`](https://github.com/retest/recheck-web/tree/master/src/test/java/de/retest/web/testutils) is internal for testing purposes. May I ask what you need from there?

**Comment by Wollewoll** [comment]
I play a little bit with your tool and would inplement this in my Project, and found it, not more... :-)

![grafik](https://user-images.githubusercontent.com/48954586/55075626-ba72a180-5093-11e9-8c9a-a52b9ea08e1f.png)

**Comment by beatngu13** [comment]
I see, but as I said, this is only for internal testing purposes as it is under `src/test`. However, it is open source, so feel free to reuse it. ✌️
