### ISSUE TITLE
Unwrap UnbreakableDriver before 3rd party calls

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck-web#278]
We should always unwrap `UnbreakableDriver` instances before we pass them to 3rd party libs. #277 does this for screenshots because the problem here was that Shutterbug internally uses `instanceof` checks to adapt the screenshot behavior e.g. in the case of `ChromeDriver`. However, since `UnbreakableDriver` is never `true` for `instanceof` checks on default `WebDriver` types, we caused false behavior. This lead to broken tests as Shutterbug didn't scroll back to the top of the page, causing `WebElement`s not being clickable anymore.

**Comment by beatngu13** [comment]
This may also be worth mentioning in our docs if, for instance, users pass the driver to other libs, which is not under our control.

**Comment by diba1013** [comment]
This behaviour then seems then like a code smell or at least bad API behaviour (not only from our side). As the purpose of a [Decorator](https://en.wikipedia.org/wiki/Decorator_pattern) is to expand the function of the wrapper class (i.e. make it unbreakable), one should think, that it can be used as the base class.

The UnbreakableDriver would then just be used as a fancy way of looking up elements with `. As I don't really know Selenium myself that well, isn't this a more complex `By`? @roesslerj maybe you know more as you implemented it ... .

We should therefore also consider to make this more transparent and easy which drivers get created and how to use them.

**Comment by beatngu13** [comment]
Related issues due to wrapped Selenium classes:

* #288
* #290

**Comment by javydreamercsw** [comment]
It's causing issues already and I wouldn't be surprised more will keep hoping out. I would consider it a bug at this point.

**Comment by roesslerj** [comment]
Addressed in PR https://github.com/retest/recheck-web/pull/306

**Comment by beatngu13** [comment]
Closed as we now implement `WrapsDriver` (and `WrapsElement`), which should be handled by 3rd party libs.

**Comment by javydreamercsw** [comment]
Which version will contain all this changes?

**Comment by roesslerj** [comment]
We'll have a version 1.3.1 asap and let you know.

**Comment by roesslerj** [comment]
Due to issues with the build pipeline, will be released on Monday.

**Comment by roesslerj** [comment]
recheck-web 1.3.1 should soon be available on maven central.
