### ISSUE TITLE
Provide a way to access the wrapped WebElement on WebElementWrapper

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#288]
It would be helpful to be able to access the wrapped WebElement from WebElementWrapper.

This will allow me to work around issues like this when trying to execute a script:

`Argument is of an illegal type: de.retest.web.selenium.WebElementWrapper`

This seems straight forward so I'll have a PR shortly.

**Comment by roesslerj** [comment]
Great, thanks! Looking forward to your PR :-)

**Comment by roesslerj** [comment]
Addressed with PR #293.
