### ISSUE TITLE
Inserted and deleted elements aren't recognized anymore

### ISSUE THREAD

**Issue by beatngu13** [retest/recheck-web#295]
Appears to be a regression for which we don't have tests (i.e. verify insertion, change, and deletion yield a test failure).

Steps to reproduce:

1. Execute e.g. `CenterTestIT` and verify it passes locally
2. Delete the `<div>` (ID "center") in lines 35 – 37 from `src/test/resources/pages/centered.html`
3. Run the test again, it passes (although it should fail)

In contrast, if you change the data of the `<div>` (e.g. adapt the text content), then the test fails as expected.

**EDIT:** Inserted elements also seem to be affected. If you simply add another `<div>` to the `<body>`, the test passes too.

**Comment by roesslerj** [comment]
Should be addressed with https://github.com/retest/recheck/pull/343 in recheck 1.3.1.
