### ISSUE TITLE
Have equivalence classes

### ISSUE THREAD

**Issue by roesslerj** [retest/recheck-web#30]
We want classes of attribute equivalence.

E.g. one system has font "Times", another "Times New Roman", and they should be equivalent. Same for rounding errors of sub-pixel size, margin, padding, etc. Or cursor "pointer" and "null"—just to name a few.

and {clip = [expected=rect(0px, 0px, 0px, 0px), actual=rect(0px 0px 0px 0px)]}

**Comment by diba1013** [comment]
We will track this internally.
