### ISSUE TITLE
Version 1.5.0-beta1: AutocheckingRecheckDriver constructor changed

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#349]
Started giving it a try and noticed that the AutocheckingRecheckDriver constructor changed. There seems to no longer be a way to set a naming strategy. In my case I used to pass a custom AutocheckingCheckNamingStrategy and that's no longer possible it seems.

Created from #326

**Comment by diba1013** [comment]
_In response to [comment](https://github.com/retest/recheck-web/issues/326#issuecomment-531232327):_

I tested on [v1.5.0-beta.1](https://github.com/retest/recheck-web/tree/v1.5.0-beta.1) and it seems to work, such as that I can access the underlying [RecheckOptionsBuilder](https://github.com/retest/recheck/blob/release/v1.5.0/src/main/java/de/retest/recheck/RecheckOptions.java#L147). Thus I am able to both pass a `AutocheckingCheckNamingStrategy` and a `FileNamerStrategy` (deprecated and superseded by [ProjectLayout](https://github.com/retest/recheck/blob/release/v1.5.0/src/main/java/de/retest/recheck/persistence/ProjectLayout.java) and [NamingStragegy](https://github.com/retest/recheck/blob/release/v1.5.0/src/main/java/de/retest/recheck/persistence/NamingStrategy.java)  as `projectLayout` and `namingStrategy` respectively).
```
RecheckWebOptions.builder() //
			.checkNamingStrategy( new CustomCheckNamingStrategy()  ) //
			.fileNamerStrategy( new CustomNamingStrategy() ) //
			.build()
```
However, as the builders are not that robust, you need to make sure to set all specific `ReckeckWebOptions` (i.e. `AutocheckingCheckNamingStrategy`) before you proceed to the common `RecheckOptions`.

If you still have the issue or I misunderstood something, please provide additional information.
