### ISSUE TITLE
Golden master cannot be found

### ISSUE THREAD

**Issue by diba1013** [retest/recheck-web#352]
![Screen Shot 2019-09-17 at 7 42 07 AM](https://user-images.githubusercontent.com/2817343/65042546-ac089280-d91e-11e9-829b-39bdbfddad2d.png)
No accept/ignore/apply for differences either.

_Originally posted by @javydreamercsw in https://github.com/retest/recheck-web/issues/326#issuecomment-532203303_

**Comment by diba1013** [comment]
@javydreamercsw mentioned that this might be related to spaces _[#326  (comment)](https://github.com/retest/recheck-web/issues/326#issuecomment-532209892)_

### My test setup

1. Insert spaces with `FileNamerStrategy#getTestClassName` and `FileNamerStrategy#getTestMethodName` using `MavenConformFileNamerStrategy`.
2. Insert spaces in `RecheckOptionsBuilder#suiteName` and `Recheck#startTest`.

I create a test which introduces differences within two checks, expecting a report being created which is printed to console after test execution and can be opened with review.

Results with [recheck-v1.4.0](https://github.com/retest/recheck/tree/v1.4.0) (as used in recheck-web-1.4.0)
1. & 2. Properly creating a golden master as expected
* console: Proper output
* review: Proper report

Results with [recheck-1.5.0-beta.2](https://github.com/retest/recheck/tree/v1.5.0-beta.2) (as used in recheck-web-1.5.0-beta.2) and [recheck-1.5.0-beta.5](https://github.com/retest/recheck/tree/v1.5.0-beta.5) (currently not released as recheck-web)
1. Properly creating a golden master as expected
2. Missing golden master

### Findings

This means, that we messed up something when providing a custom suite name (probably introduced with retest/recheck#411). However, the `FileNamerStrategy` does not fail.

A a result I fixed above error, where the path to the golden master was not properly created, and the test passes with the expected output. However, both the console and review were able to properly display the differences or throw a exception when there is no golden master.

### Conclusions

We will provide a new recheck, recheck-web and review beta in the next days. review will include a new feature where it properly checks your license and if a golden master is available and displays a corresponding message. This will help you to narrow down the problem.

--

What I kindly ask from you, as I was not able to recreate your exact problem:
1. Could you verify that you still have an evaluation license? This should be displayed, once you login on [retest.de](https://retest.de/) and click on _Subscription_. Right above should be a text that displays your remaining time; you do not need to insert any more data.
2. Could you elaborate some more on your setup (RecheckOptions, where there is a space, etc.)?

**Comment by javydreamercsw** [comment]
![Screen Shot 2019-09-18 at 8 13 26 AM](https://user-images.githubusercontent.com/2817343/65151690-35d26180-d9ec-11e9-9904-acdd203e8b6f.png)
I got the screen above when clicked on the subscriptions tab.

**Comment by javydreamercsw** [comment]
The space was when I started the test:
`getRecheck().startTest("Add User");`

**Comment by diba1013** [comment]
> I got the screen above when clicked on the subscriptions tab.
Unfortunately, I was unable to get the error from our log system thus cannot tell what went wrong there. @roesslerj can you verify the license?

> The space was when I started the test
Ok, that is what I did and I could not reproduce it. Usually Windows (the OS I am using) is known to have more problems in this type of matter.

As stated above, we will be releasing a new version of recheck-web and review soon. The latter has a couple improvements which should tell you, why you can't edit the report. Secondly it should display the path to the golden master in the `check`-Elements (i. e. `add-username`).

I will inform you, once these versions are available.

**Comment by diba1013** [comment]
We now have new beta versions for our products.
* recheck-web: https://github.com/retest/recheck-web/releases/tag/v1.5.0-beta.3
    * Fix custom suite names not being used for golden masters.
* review: https://assets.retest.org/releases/review/review-1.5.0-beta.4.zip
    * Display why the golden master cannot be edited.
    * Display the path to the golden master if available.

Could you execute your test again and view it with review. It would help if you attached a screenshot. Please feel free to hide any sensible data.

**Comment by javydreamercsw** [comment]
Test don't work the same any more. Neither RecheckImpl or RecheckWebImpl accept a web element as before.
`java.lang.UnsupportedOperationException: No recheck adapter registered that can handle an object of class com.sun.proxy.$Proxy32.`
Did something else change?

**Comment by roesslerj** [comment]
Problem is probably related to https://github.com/retest/recheck-web/issues/350. Can you give the qualified class of the WebElement, together with the Selenium version you are using?

**Comment by javydreamercsw** [comment]
Selenium 3.141.59. There's no fully qualified class for the Webelement. That's created from the @FindBy annotation.

**Comment by javydreamercsw** [comment]
I reverted to beta 2 and can confirm that review can open the report now and that the checkboxes show up.

**Comment by javydreamercsw** [comment]
That said it behaves still weird
![Screen Shot 2019-09-19 at 8 46 27 AM](https://user-images.githubusercontent.com/2817343/65249657-fbcf9100-dab9-11e9-8612-3b6781926a7f.png)

You can select all checkboxes and apply doesn't seem to change any files.

**Comment by javydreamercsw** [comment]
Apply changes only shows up if Ignore element permanently is checked.

**Comment by beatngu13** [comment]
> Test don't work the same any more. Neither RecheckImpl or RecheckWebImpl accept a web element as before.
> `java.lang.UnsupportedOperationException: No recheck adapter registered that can handle an object of class com.sun.proxy.$Proxy32.`
> Did something else change?

@javydreamercsw that's a regression in the current beta—sorry! We'll keep you updated in the corresponding issue #326.

**Comment by diba1013** [comment]
> That said it behaves still weird
> You can select all checkboxes and apply doesn't seem to change any files.

If I recall correctly, at the moment the GUI expects only one checkbox to be active at a time for apply.

If you have differences accepted or ignored and hit apply (assuming it is visible), the GUI should tell you what files have been updated (if any).
Do you use a VCS like git? Did you stage or commit the golden masters and recheck.ignore before applying (i. e. do changes show up)?. This is the key indicator if the apply works. Simply executing the test a second time might not work, since there could be elements changing all the time (e.g. https://google.com). For this to work, you would have to ignore those changing elements or single attributes.

> Apply changes only shows up if Ignore element permanently is checked.

There is a mechanism in place that tries to observe what checkboxes are clicked. It is known to fail, if you want it to, especially with ignoring checkboxes. I will try to incorporate a workaround for that. _Note that this might not fix the problem._

**Comment by javydreamercsw** [comment]
Yes, we use git. There was no summary of the modified changes and git didn't show any either.

**Comment by diba1013** [comment]
Well that is strange, indeed. At least the recheck.ignore should have been updated. However I could (again sadly) not recreate it. Is there any specific order you click the checkboxes or is it reliable no matter what single checkboxes you click?

Could you verify that a `recheck.ignore` is loaded such that a project could be identified?
![ignore-view](https://user-images.githubusercontent.com/10256143/65324143-a5db1600-dbab-11e9-889d-911023c87419.png)

**Comment by diba1013** [comment]
We have a new review beta: https://assets.retest.org/releases/review/review-1.5.0-beta.5.zip

- Fix the "Apply" Button disappearing.

**Comment by javydreamercsw** [comment]
Seems to be working fine again.

Noticed this error messages when looking at some diffs within review.

 ```
08:21:51.062 ERROR [pool-5-thread-2] [de.retest.recheck.ui.image.ImageUtils] - X value of image to cut 595 is outside of bigger image with width 290!
 08:21:51.062 ERROR [pool-5-thread-1] [de.retest.recheck.ui.image.ImageUtils] - X value of image to cut 595 is outside of bigger image with width 290!
 08:21:51.064 ERROR [pool-5-thread-2] [de.retest.recheck.ui.image.ImageUtils] - Cannot create mark at x value 595 with in image of width 290.
 08:21:51.064 ERROR [pool-5-thread-1] [de.retest.recheck.ui.image.ImageUtils] - Cannot create mark at x value 595 with in image of width 290.
 08:21:54.390 ERROR [pool-5-thread-2] [de.retest.recheck.ui.image.ImageUtils] - X value of image to cut 595 is outside of bigger image with width 290!
 08:21:54.390 ERROR [pool-5-thread-1] [de.retest.recheck.ui.image.ImageUtils] - X value of image to cut 595 is outside of bigger image with width 290!
 08:21:54.392 ERROR [pool-5-thread-2] [de.retest.recheck.ui.image.ImageUtils] - Cannot create mark at x value 595 with in image of width 290.
 08:21:54.392 ERROR [pool-5-thread-1] [de.retest.recheck.ui.image.ImageUtils] - Cannot create mark at x value 595 with in image of width 290.
```
I can send the file for inspection to a private email or something.

**Comment by diba1013** [comment]
> Seems to be working fine again.
Great.

> Noticed this error messages when looking at some diffs within review.
This is a known problem internally, which is related to the bounding boxes of elements and their screenshots.
