### ISSUE TITLE
Link in recheck.ignore file leads to a 404

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#358]
The generated recheck.ignore file has the following link:

https://retest.github.io/docs/recheck/how-ignore-works-in-recheck/

Which leads to a 404.

**Comment by diba1013** [comment]
The [link](https://docs.retest.de/recheck/how-ignore-works/) changed a while back. This should already have been adopted in an earlier [release of recheck](https://github.com/retest/recheck/blob/master/src/main/resources/default-recheck.ignore#L19). However, we do not overwrite your `recheck.ignore` as we do not discard your potential manual changes.

Secondly, the wiki is a work in progress. Links and pages may change without notice as we try to constantly improve and expand the documentation.

**Comment by roesslerj** [comment]
Well ... maybe we should put a redirect there?

**Comment by diba1013** [comment]
This is fixed now with a redirect. You should not have to adjust anything on your side.
