### ISSUE TITLE
NoElementWithHighEnoughMatchFoundException: The element input from the Golden Master could not be matched with high enough confidence.

### ISSUE THREAD

**Issue by javydreamercsw** [retest/recheck-web#417]
## Describe the Bug

Running test with golden files from 1.5.0 leads to the following error in most cases:

`de.retest.web.selenium.NoElementWithHighEnoughMatchFoundException: The element input from the Golden Master could not be matched with high enough confidence.`

### How to Reproduce?

1. Run test with 1.5.0 to create golden files.
2. Re-run with 1.6.0.

### Setup

- recheck-web: 1.6.0
- Selenium version: 3.141.59
- Testing framework: TestNG 7.0.0
- OS: MacOS 14
- Java version: OpenJDK 11

### Additional Context

N/A

**Comment by javydreamercsw** [comment]
Using AutocheckingRecheckDriver.

**Comment by diba1013** [comment]
Could you please provide the first lines of the stacktrace, so that we can narrow down the cause of this bug? Our tests did not reveal such an issue. @roesslerj could give some insight.

**Comment by javydreamercsw** [comment]
So far I've been unable to reproduce the error. I'll update if/when I'm able to.

**Comment by roesslerj** [comment]
None the less, I tried to improve the error message to be more actionable for users. See https://github.com/retest/recheck-web/pull/422
