### ISSUE TITLE
Aggregate Insert Changes

### ISSUE THREAD

**Issue by roesslerj** [retest/recheck-web#46]
Multiple inserted elements should be summarized. E.g. instead of 
`TR: [expected=null, actual=TR], TD [sunscreen]: [expected=null, actual=TD [sunscreen]], TD [2.02]: [expected=null, actual=TD [2.02]]`

We want a `TR (with 2 child elements): [expected=null, actual=sunscreen 2.02]`

**Comment by beatngu13** [comment]
Isn't this a GUI/CLI task?

**Comment by roesslerj** [comment]
It has become one :-D
