### ISSUE TITLE
Wait for angular rendering

### ISSUE THREAD

**Issue by martin-v** [retest/recheck-web#658]
## Problem

recheck don't work well with angular, because page is not reloaded but changed inside.

### Solution

I found this js script implementing a waitForAngular method.
https://github.com/angular/blocking-proxy/blob/master/lib/client_scripts/wait.js
It is used in the same context (testing angular pages) so it should do what we need.

It will return directly if no angular app is present, so we can integrate it for all pages.

Any opinions about that @diba1013 and @roesslerj ?

**Comment by diba1013** [comment]
Waiting for a page to be stable is a general problem, and might be even more so for single page applications (SPA). Selenium tries its best and provides some timeout functions, but understandably, it cannot cover each use case.

In the past, we issued that the user must ensure to [wait for the page to be ready](https://docs.retest.de/recheck-web/introduction/usage/#best-practices). However, when using an autochecking driver this is not really possible as there is no way to wait after an action is executed and before the check is made.

This could be solved by introducing a hook for that which gets executed in between. This could be either in the `AutocheckingDriver#check` or included in the `RecheckWebImpl#check` step.

1. Using an framework-specific hook should be fairly easy, but comes with some costs:
    1. It will only work for the specific framework. 
    1. If this is a general flaw of using SPA, we would have to include and execute each and every hook which may cause a significant slowdown (even if it returns instantly) because of the additional traffic. 
    1. Furthermore, we would have to maintain this script file (i.e. copy it every so often).

1. Using a generic hook (e.g. path to a JavaScript file, may be configurable or static) might cover more use cases, but:
    1. It is confusing for the user, and we would have to potentially provide a link to the script above anyway.
    1. It is more complex, both in implementation and in usage.

I am undecided, which way would be the best. The former would be more easy, work for your use case and require maintaining effort. The latter would require more implementation effort with potentially not much benefit to gain.

**Comment by martin-v** [comment]
Here is a WebDriver wrapper with wait for angular function https://github.com/paul-hammant/ngWebDriver which is a simple solution.
